[package]
name = "mpp"
version = "0.1.0"
edition = "2021"

[dependencies]
curve25519-dalek = "4.1.2"
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
rand = "0.8.5"
zk-callbacks = { git = "https://github.com/hkailad/callbacks", version = "0.1.0" }
